version: '3.8'

services:
  client:
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      server_mynetwork:
        ipv4_address: 172.19.0.3

networks:
  server_mynetwork:
    external: true
